services:
  backend:
    image: registry.gitflic.ru/project/ivakorin/garage-management/garage-management:latest
    container_name: garage-management
    ports:
      - "127.0.0.1:8000:80"
    environment:
      - GM__REDIS__HOST=${GM__REDIS__HOST}
      - GM__REDIS__PORT=${GM__REDIS__PORT}
      - GM__MQTT__HOST=${GM__MQTT__HOST}
      - GM__MQTT__PORT=${GM__MQTT__PORT}
      - GM__MQTT__USERNAME=${GM__MQTT__USERNAME}
      - GM__MQTT__PASSWORD=${GM__MQTT__PASSWORD}
      - GM__APP_SETTINGS__KEEP_DATA=${GM__APP_SETTINGS__KEEP_DATA}
      - GM__LOG__LEVEL=${GM__LOG__LEVEL}
    volumes:
      - ./base:/app/db/base
      - ./plugins:/app/plugins
    networks:
      - iot-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/docs" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: registry.gitflic.ru/project/ivakorin/garage-management/garage-management-frontend:latest
    container_name: garage-management-frontend
    ports:
      - "81:80"
    environment:
      - GM__BACK__API__URL=${GM__BACK__API__URL}
      - GM__BACK__WS__URL=${GM__BACK__WS__URL}
    networks:
      - iot-network
    restart: unless-stopped
    depends_on:
      - backend

  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    environment:
      - GM__MQTT__USERNAME=${GM__MQTT__USERNAME:-mqtt}
      - GM__MQTT__PASSWORD=${GM__MQTT__PASSWORD:-mqtt}
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
      - ./mosquitto/init-mqtt.sh:/usr/local/bin/init-mqtt.sh:ro
    command: [ "/usr/local/bin/init-mqtt.sh" ]
    networks:
      - iot-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mosquitto_sub", "-t", "$SYS/broker/uptime", "-C", "1", "-h", "localhost", "-p", "1883" ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: redis-db
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data:rw
    networks:
      - iot-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -p 6379 ping | grep PONG" ]
      interval: 30s
      timeout: 10s

networks:
  iot-network:
    name: iot-network
    driver: bridge
